version: '3.8'

services:
  mc-server:
    build: .
    container_name: mc-neoforge-server
    ports:
      - "25565:25565"
    volumes:
      - ./world:/server/world
      - ./backups:/server/backups
    restart: unless-stopped